# Generated by Django 3.2.6 on 2021-11-07 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0002_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
    ]
