# Generated by Django 3.2.6 on 2021-11-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0003_auto_20211106_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='rating',
            new_name='avg_rating',
        ),
        migrations.AddField(
            model_name='book',
            name='times_rated',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='total_rating',
            field=models.FloatField(default=5),
        ),
    ]
