# Generated by Django 3.2.6 on 2021-11-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0004_auto_20211107_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='total_rating',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=65),
        ),
    ]
