# Generated by Django 3.2.6 on 2021-12-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0015_usercart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
